### ISSUE TITLE
gpx_Trino_linux_amd64 not found

### ISSUE THREAD

**Issue by amendge** [trinodb/grafana-trino#163]
logger=plugin.loader t=2023-02-08T05:59:45.25603939Z level=error msg="Could not start plugin" pluginId=trino-datasource err="fork/exec /var/lib/grafana/plugins/trino/src/gpx_Trino_linux_amd64: no such file or directory"
Where is this file gpx_Trino_linux_amd64?

**Comment by nineinchnick** [comment]
How are you trying to run Grafana with this plugin? If you're building it yourself, are you following the steps from https://github.com/starburstdata/grafana-trino/blob/main/DEVELOPMENT.md ?

**Comment by nineinchnick** [comment]
Can you answer my questions?

**Comment by amendge** [comment]
@q-onuii I have solved the problem and you can follow the process with this document(https://github.com/starburstdata/grafana-trino/blob/main/DEVELOPMENT.md) and at the end copy gpx_Trino_linux_amd64 into the src directory
for dockerfile:
FROM grafana/grafana-oss
USER root
COPY ./plugins/trino  /var/lib/grafana/plugins/trino
and others

**Comment by amendge** [comment]
@nineinchnick It may be unfriendly to the user to still need to compile. Could you provide a tag version for used in grafana plugins？thx!

**Comment by nineinchnick** [comment]
I just created a new pre-release and you can find a zip there: https://github.com/trinodb/grafana-trino/releases/tag/v1.0.0-beta.3

Note that this built is unsigned, I'll submit it again to Grafana for verification, and hopefully we'll receive a signing key soon.

**Comment by amendge** [comment]
@nineinchnick @q-onuii  sry，i forget it, you can edit grafana.ini  and edit this! it can resolve unsigned.
`[plugins]
enable_alpha = true
allow_loading_unsigned_plugins = trino-datasource`
