### ISSUE TITLE
Fetch error: 404 Not Found Instantiating http://localhost:3000/public/plugins/trino-datasource/module.js Loading plugins/trino-datasource/module

### ISSUE THREAD

**Issue by raulykoto** [trinodb/grafana-trino#181]
Got this error when trying docker:
![test](https://user-images.githubusercontent.com/128640110/227028814-dfd66fbf-8eac-4aa8-8a46-d8836c201ecd.png)

**Comment by nineinchnick** [comment]
Can you give more details on how you're running it?

**Comment by raulykoto** [comment]
Im running local:

docker run -d -p 3000:3000 \
  -v "$(pwd):/var/lib/grafana/plugins/trino" \
  -e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=trino-datasource" \
  --name=grafana \
  grafana/grafana-oss
