### ISSUE TITLE
Publishing to Grafana Plugins

### ISSUE THREAD

**Issue by majunting** [trinodb/grafana-trino#188]
Hi, thank you for developing this plugin. I have tested it locally in Docker environment, and it worked perfectly. May I check if you have any plan to publish this plugin on Grafana Plugins so that more users can discover and use this plugin?

**Comment by nineinchnick** [comment]
We're in the middle of reviewing the plugin by Grafana. This is the last blocking item required to pass the review: https://github.com/trinodb/trino-go-client/pull/73

**Comment by nineinchnick** [comment]
https://grafana.com/grafana/plugins/trino-datasource/
