### ISSUE TITLE
query based variables

### ISSUE THREAD

**Issue by pdmangel2** [trinodb/grafana-trino#197]
I succeeded in setting up grafana:9.4.7 with the grafana-trino-plugin and got some basic dashboard workin.
But when trying to create a query based variable I don't see a text box to enter a query.

**Comment by renan-magnussao** [comment]
Hi @pdmangel2!

I'm facing the same issue. Were you able to do this somehow?

**Comment by pdmangel2** [comment]
No, we left the trino path for various reasons, This issue is one of them.
