### ISSUE TITLE
Enable alerting support

### ISSUE THREAD

**Issue by Amit-Hora** [trinodb/grafana-trino#246]
@nineinchnick  are there any plans to support alerting? . Can you share changes we need to make this feature available 
Thanks,

**Comment by nineinchnick** [comment]
There are no plans but we're open for contributions.

**Comment by Amit-Hora** [comment]
I would love to . Can you please help me with some resource links. Or steps like where I need to make the change in which file . I Googled it but I was not able to find where I need to make the change like which method I need to implement. All I could find was set "alerting"-"true" for alerts to be enabled

**Comment by nineinchnick** [comment]
Sorry, I don't know myself. I used the postgresql plugin as an example when working on this, but it's built in, so sometimes it's not so straightforward.
