### ISSUE TITLE
A new query is triggered each time tab is changed

### ISSUE THREAD

**Issue by Amit-Hora** [trinodb/grafana-trino#248]
Hi @nineinchnick ,

I noticed that if I use explore tab and write some queries, each time I change the browser tab a new query is triggered . How can I avoid this behaviour , like only have query triggered if and only if RunQuery is clicked

**Comment by Amit-Hora** [comment]
I think these are two different concerns 
1. Use cache to display old data till we don't have the result
2. Avoid query to be executed if a tab is changed , make it more controllable 
Thoughts ?

**Comment by nineinchnick** [comment]
I don't know if it is possible to avoid Grafana to execute queries.

**Comment by Amit-Hora** [comment]
I could be wrong but I see in QueryEditor these two things. Does these control when to run the query ? . Can we like make it run the query only when we click on RunQuery button ?
![image](https://github.com/trinodb/grafana-trino/assets/4957640/024d7090-4293-4b64-ae66-41044adb7880)

**Comment by Amit-Hora** [comment]
I observed that this also happens if I click on query editor space and I click outside queryeditor . So each time I click the queryeditor and outside queryeditor a new query is fired

**Comment by Amit-Hora** [comment]
@mrveera do you have any idea on this ?, thanks

**Comment by nineinchnick** [comment]
Fixed by #252
