### ISSUE TITLE
Adding Trino as DataSource in Annotations

### ISSUE THREAD

**Issue by BigUV** [trinodb/grafana-trino#253]
Hi,

1st thanks a lot for the amazing and super useful add-on!
Really helps us in so many cases.

Is it possible to add it as a DataSource also to the Annotations? 
(Adding it to the Variables in Ver 1.0.4 was awesome)

Thx
![666](https://github.com/trinodb/grafana-trino/assets/63048931/36da4e38-148f-4c54-8f12-d4ac4e53db89)

**Comment by nineinchnick** [comment]
Should be fixed by #262

**Comment by BigUV** [comment]
Thanks a lot!
Highly appreciated
