### ISSUE TITLE
Plugin not working on grafana

### ISSUE THREAD

**Issue by hobbitx** [trinodb/grafana-trino#255]
Hi folks, we are using the plugin in Grafana, but the latest version ( `1.0.5` ) is not working.

When we click to run the query, for example, nothing is running. 
Doing an initial debug, it seems that the query editor is not updating with the new query we wrote.

It may be related to this [change](https://github.com/trinodb/grafana-trino/issues/248).

The last version ( `1.0.4`) is working however with the problem described in the commented issue, updating at all times.

Grafana version: `9.5.13`

**Comment by nineinchnick** [comment]
I reverted that change in https://github.com/trinodb/grafana-trino/commit/7739431e8efd4f638a163d6bc3455b8bddc9e22e and I'm releasing 1.0.6. Sorry it took so long and thanks for reporting this!
