### ISSUE TITLE
presto supports this plugin?

### ISSUE THREAD

**Issue by frank-lam** [trinodb/grafana-trino#260]
Whether Trino's grafana plugin is compatible with presto data sources?

Trino plugin for Grafana | Grafana Labs
https://grafana.com/grafana/plugins/trino-datasource/

**Comment by nineinchnick** [comment]
I don't know, can you try it?

**Comment by nineinchnick** [comment]
The Trino Go driver used here uses different http headers than Presto, so I wouldn't expect it to work. Maybe try asking on the Presto Slack.
