### ISSUE TITLE
Support for custom HTTP headers

### ISSUE THREAD

**Issue by llamafilm** [trinodb/grafana-trino#263]
Our Trino cluster requires JWT authentication which can be sent as an HTTP header in the form of `Authorization: Bearer $TOKEN`.  The Trino datasource settings page shows a button to add custom HTTP headers, but when I try that it fails:

> grafana  | logger=context userId=1 orgId=1 uname=admin t=2024-09-06T19:33:34.510609046Z level=error msg=InternalError error="[plugin.downstreamError] client: failed to query data: Failed to query data: rpc error: code = Unknown desc = error reading settings: Custom headers are not supported and must be not set" remote_addr=xxxxxxxxx traceID=

It would be awesome to get this feature added, as it's the only way my company allows external Trino access.

**Comment by jschroth** [comment]
This specific issue would be solved by https://github.com/trinodb/grafana-trino/pull/268

**Comment by jschroth** [comment]
This specific issue was solved in https://github.com/trinodb/grafana-trino/pull/274
