### ISSUE TITLE
Implement OAuth 2

### ISSUE THREAD

**Issue by nineinchnick** [trinodb/grafana-trino#32]
Enable forwarding OAuth tokens and handle them in the backend to pass them into the driver.

**Comment by harksin** [comment]
anyone working on this already ?

**Comment by nineinchnick** [comment]
I'm not aware of anyone working on it. Any contributions are very appreciated!

**Comment by harksin** [comment]
hello :wave: 
@kalil-pelissier & I are working on it on [nudibranches tech](https://nudibranches.tech/) side
we should hopefully be able to provide a PR next week.
Is there anyone here we could ask if we need some help?
