### ISSUE TITLE
Enable SSL authentication

### ISSUE THREAD

**Issue by DanielGarcia117** [trinodb/grafana-trino#86]
Hello and thank you for this plugin. Does it support connecting to a SSL-enabled Trino service? I tried pasting the certificate in "TLS/SSL Auth Details" after enabling "With CA Cert" and introducing basic auth credentials, but I get the following when testing:
![image](https://user-images.githubusercontent.com/94969544/185067970-8a70805d-06db-4839-a979-a7bf40e52062.png)

**Comment by nineinchnick** [comment]
Can you check the server logs for more details? You might have to enable debug logs to get any meaningful error.

**Comment by DanielGarcia117** [comment]
It's a plain ssl handshake error. Is SSL auth enabled?
